spring:
  datasource:
    url: jdbc:mysql://localhost:3306/my_blog?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: localhost
    port: 6379

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      table-prefix: my_
  # type-enums-package: com.lmh.secondhandbook.enums
server:
  port: 8888